apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fcg-games-api-ingress
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /games
            pathType: Prefix
            backend:
              service:
                name: fcg-games-api-service
                port:
                  number: 80